### ISSUE TITLE
GISAID metadata

### ISSUE THREAD

**Issue by Laplace3210** [saketkc/covmuller#1]
I used the function FilterGISAIDIndia to filter GISAID India Metadata, but it showed error like that:

> FilterGISAIDIndia(gisaid_metadata_all)
Error in filter(., Country == "India") : 
  object 'gisaid_metadata_all' not found

Is it mean that the metadata in GISAID is not avaliable now?

**Comment by saketkc** [comment]
You will need to download the metadata tarball from the GISAID website. Sorry, the documentation could definitely be improved.

**Comment by Laplace3210** [comment]
It may sound silly but I have to ask: where is the "metadata tarball" in GISAID? I could not find it...

**Comment by saketkc** [comment]
It is under "Downloads -> metadata" 
![image](https://user-images.githubusercontent.com/682153/176842037-3e878de1-da96-44ae-b5fc-334ee20ce51b.png)

**Comment by Laplace3210** [comment]
Why the interface is different with you. Is it becasue we are in the different region?
![1656678465109](https://user-images.githubusercontent.com/50813700/176896629-3e0c8308-ab15-48ba-a346-2a5d524b9e07.png)

**Comment by saketkc** [comment]
Not really sure about that. You could check with gisaid help desk.

**Comment by Laplace3210** [comment]
Thank you very much for your patiently explanation
